
const actionTypes = {
  ADD_TODO: 'ADD_TODO',
  TOGGLE_TODO: 'TOGGLE_TODO',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_ACTIVE: 'SHOW_ACTIVE',


  ADMIN_ADD_LANGUAGE: 'ADMIN_ADD_LANGUAGE',
  ADMIN_EDIT_LANGUAGE: 'ADMIN_EDIT_LANGUAGE',
  ACTIVATE_LANGUAGE: 'ACTIVATE_LANGUAGE'
}

export default actionTypes
